//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurrance
    {
        public long InsurranceId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<int> SocialInsuranceNumber { get; set; }
        public Nullable<System.DateTime> SocialInsuranceProvidedDate { get; set; }
        public string SocialInsuranceProvidedAddress { get; set; }
        public Nullable<int> HealthInsuranceNumber { get; set; }
        public Nullable<System.DateTime> HealthInsuranceProvidedDate { get; set; }
        public string HealthInsuranceProvidedAddress { get; set; }
    }
}
